### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by chuckak** [ben-z/Silent-Sync#10]
1. Install silent-sync
2. Setup a silent-sync.json file as shown below
3. Restart Atom

``` json
{
  "enabled": true,
  "host": "site.com",
  "port": 321,
  "username": "user",
  "remoteDir": "/home/user/subfolder/sub.folder",
  "deleteRemoteFiles":false,
  "rsyncFlags": "azP"
}
```

**Atom Version**: 0.210.0
**System**: linux 4.0.5-1-ARCH
**Thrown From**: [silent-sync](https://github.com/ben-z/Silent-Sync) package, v1.2.1
### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /home/user/.atom/packages/silent-sync/lib/silent-sync-view.coffee:63

TypeError: Cannot read property 'indexOf' of undefined
    at Object.filter (/home/user/.atom/packages/silent-sync/lib/silent-sync-view.coffee:97:40)
    at /home/user/.atom/packages/silent-sync/node_modules/watch/main.js:53:44
    at FSReqWrap.oncomplete (fs.js:77:15)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": []
  },
  "silent-sync": {
    "useConfigFile": true,
    "enabled": false,
    "notifyMissingConfig": true
  }
}
```
### Installed Packages

``` coffee
# User
language-rust, v0.4.3
minimap, v4.10.0
seti-ui, v0.7.1
silent-sync, v1.2.1

# Dev
No dev packages
```

**Comment by ben-z** [comment]
Looks like it's due to the missing `exclude` option in the config. `include` is missing as well. Add those two keys into `silent-sync.json` and make them empty arrays if they are not needed.

Let me know how it goes!

Ben
