### ISSUE TITLE
Sync when save

### ISSUE THREAD

**Issue by eigan** [ben-z/Silent-Sync#11]
I test my code on a remote dev machine right after save. It would be sweet if this plugin syncs right after I save instead of up to 4-5 seconds.

**Comment by eigan** [comment]
I have never written coffescript or any atom package before, but this seems to work.

I added the following after `@state.connected = true` in lib/silent-sync-view.coffee line 140.

``` coffescript
        atom.workspace.observeTextEditors (editor) =>
            editor.onDidSave =>
                @upload()
```

Note that it will sync two times, one for the did-save event, and one for the file change event. This is probably not the way the author would implement it. But it works until he might add this feature :)

**Comment by ben-z** [comment]
@eigan this is a great suggestion! I should somehow modify the watcher to be more spontaneous.

**Comment by hultberg** [comment]
@eigan: Add PR?
