### ISSUE TITLE
It does not read the silent-sync.json when opening folder

### ISSUE THREAD

**Issue by horta** [ben-z/Silent-Sync#4]
Hello,

First of all, thanks for the package! =)

So the silent-sync.json is not read when I open a folder by using Atom's menu: File -> Open

**Comment by ben-z** [comment]
Hello @Horta,

Please make sure you have checked the `Use configuration file` option in the preferences.

If you would like to suppress the missing configuration file warning for projects that don't use silent-sync, disable `Missing configuration file notification` in the preferences.

Thank you for using **Silent Sync**, if you have any more questions please feel free to ask them!

Ben

**Comment by horta** [comment]
Hello ben-z,

The `Use configuration file` is set to `true`. The problem is really that Silent Sync doesn't kick in when I do the following:
1. Click on the Atom icon in the dock (os x yosemite)
2. Click File
3. Click Open File...
4. Select a project with silent-sync.json in the root and open

The Silent Sync doesn't kick in.

However, when I go to project's folder by the terminal and type `Atom .`, everything works fine... The SilentSync appears in the bottom Atom bar.

Hope I have help somehow...

Danilo

**Comment by ben-z** [comment]
Hello @Horta,

Thank you very much for this detailed description! I see that the problem is that Silent Sync was not detecting directory changes—it is now!

Version **1.1.5** has the feature added, please update and see if the problem still exists.

Thanks,

Ben

**Comment by horta** [comment]
I'm glad to help =)
